-- ===================================================================================
-- Project: E-Commerce Customer Churn & RFM Segmentation Pipeline
-- Component: SQL Data Cleaning & Feature Engineering
-- Description: Wrote optimized queries to clean transaction tables and build 
--              RFM (Recency, Frequency, Monetary) metrics.
-- Database Dialect: PostgreSQL / Standard SQL
-- ===================================================================================

-- STEP 1: Deduplicate Transactions and Clean Anomalies
-- Some transactions are double-submitted (duplicates) or have negative amounts.
-- We use a CTE with ROW_NUMBER() to identify and isolate duplicate rows.

WITH deduplicated_transactions AS (
    SELECT 
        transaction_id,
        customer_id,
        transaction_date::TIMESTAMP as transaction_datetime,
        transaction_date::DATE as transaction_day,
        amount,
        product_category,
        payment_method,
        ROW_NUMBER() OVER(
            PARTITION BY transaction_id 
            ORDER BY transaction_date DESC
        ) as row_num
    FROM raw_transactions
    WHERE 
        customer_id IS NOT NULL               -- Filter out orphan records
        AND amount > 0                         -- Remove negative price anomalies/refunds for core RFM
),

-- STEP 2: Aggregate Transactions to Customer Level
-- We calculate:
--  - Recency: Days since last transaction relative to a global analysis cutoff (e.g. '2026-01-01')
--  - Frequency: Total distinct transaction dates (or total transaction count)
--  - Monetary Value: Total revenue generated by the customer
--  - Tenure: Days between customer join date and first purchase

customer_transaction_metrics AS (
    SELECT 
        t.customer_id,
        MAX(t.transaction_day) as last_purchase_date,
        COUNT(DISTINCT t.transaction_id) as total_orders,
        SUM(t.amount) as total_spend,
        MIN(t.transaction_day) as first_purchase_date,
        -- Calculate Recency relative to fixed baseline (simulating post-2025 analysis date)
        ('2026-01-01'::DATE - MAX(t.transaction_day)) as recency_days
    FROM deduplicated_transactions t
    WHERE t.row_num = 1 -- Only keep deduplicated rows
    GROUP BY t.customer_id
),

-- STEP 3: Join Customer Profile Metadata
-- Enriches transaction aggregates with customer demographic information (age, country, traffic source, tenure)

customer_demographic_profiles AS (
    SELECT 
        c.customer_id,
        c.join_date::DATE as registration_date,
        c.age,
        c.gender,
        c.country,
        c.traffic_source,
        m.last_purchase_date,
        m.first_purchase_date,
        m.recency_days,
        m.total_orders as frequency,
        m.total_spend as monetary,
        (m.first_purchase_date - c.join_date::DATE) as registration_to_purchase_lag
    FROM raw_customers c
    INNER JOIN customer_transaction_metrics m 
        ON c.customer_id = m.customer_id
),

-- STEP 4: Segment Scoring (RFM Quintiles)
-- We use NTILE(5) window functions to divide customers into 5 groups for Recency, Frequency, and Monetary.
-- Note: Low Recency days are BETTER, so NTILE(5) order is DESC (lower value gets higher score).
-- High Frequency and Monetary are BETTER, so NTILE(5) order is ASC.

rfm_scores AS (
    SELECT 
        customer_id,
        recency_days,
        frequency,
        monetary,
        -- Recency: Lower is better (1 is most inactive, 5 is most active/recent)
        NTILE(5) OVER(ORDER BY recency_days DESC) as r_score,
        -- Frequency: Higher is better (1 is lowest frequency, 5 is highest)
        NTILE(5) OVER(ORDER BY frequency ASC) as f_score,
        -- Monetary: Higher is better (1 is lowest spend, 5 is highest)
        NTILE(5) OVER(ORDER BY monetary ASC) as m_score
    FROM customer_demographic_profiles
)

-- STEP 5: Consolidate RFM and Assign Segments
-- Build final analytical dataset, calculating RFM Score (e.g. 555, 111) and basic cohort tags

SELECT 
    p.customer_id,
    p.country,
    p.age,
    p.gender,
    p.traffic_source,
    p.recency_days,
    p.frequency,
    p.monetary,
    r.r_score,
    r.f_score,
    r.m_score,
    -- Concatenated RFM Text Score
    (r.r_score || r.f_score || r.m_score) as rfm_cell_score,
    -- Average RFM Score
    ROUND((r.r_score + r.f_score + r.m_score) / 3.0, 2) as rfm_average_score,
    -- Business logic segmentation labels
    CASE 
        WHEN r.r_score >= 4 AND r.f_score >= 4 AND r.m_score >= 4 THEN 'Champions'
        WHEN r.r_score >= 3 AND r.f_score >= 3 AND r.m_score >= 3 THEN 'Loyal Customers'
        WHEN r.r_score >= 4 AND r.f_score <= 2 THEN 'Recent Ingestions'
        WHEN r.r_score <= 2 AND r.f_score >= 3 AND r.m_score >= 3 THEN 'At Risk / Needs Activation'
        WHEN r.r_score <= 1 THEN 'Lost / Churned'
        ELSE 'Typical Mid-Tier Customer'
    END as customer_segment_label
FROM customer_demographic_profiles p
INNER JOIN rfm_scores r 
    ON p.customer_id = r.customer_id
ORDER BY monetary DESC;
